config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :appointments, only: [:create, :new]

  devise_for :escorts
  devise_for :clients

  root 'statics#home'
  get 'home_client' => 'clients#home'#, as: "home_client"

  authenticated :client do
    get 'profile' => 'clients#profile', as: "profile_client"
  end

  authenticated :escort do
    get 'profile' => 'escorts#profile', as: "profile_escort"
  end

  get 'escorts' => 'escorts#index'
  get 'escorts/:username' => 'escorts#show', as: "show_escort"

end

app/models/client.rb
class Client < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise  :database_authenticatable, :registerable,
          :recoverable, :rememberable, :trackable, :validatable,
          :timeoutable, :authentication_keys => [:username]
          #:confirmable

  # for generating random tokens (i.e. numbers)
  include Tokenable

  # for sending verification emails
  include VerifyEmail

  # appointments relationship
  has_many :appointments
  has_many :escorts, through: :appointments

  validates :username, presence: true
  validates :username, uniqueness: true, if: -> { self.username.present? }
  validates :name, presence: true
  validates :dob, presence: true
  validates :line1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :state, format: {with: /(^[A-Z]{2}$)/}, if: -> { self.state.present? }
  validates :zip, presence: true
  validates :zip, format: { with: /(^\d{5}$)|(^\d{5}-\d{4}$)/}, if: -> { self.zip.present? }

  validates :terms_of_service, acceptance: true # terms of service must be accepted

  def email_required?
    false
  end

  def email_changed?
    false
  end

  # only allow login if account is verified (by us)
  def active_for_authentication?
    super && self.verified
  end

  private

end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_filter :authenticate_client!, only: [:profile]

  def profile
    @client = current_client
    @past_appointments = @client.appointments
  end

  def home
    if !client_signed_in?
      redirect_to root_path
    end

    gon.page = @page

  end
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/views/clients/home.html.haml
= include_gon

#clients
  .container
    %div
      = link_to root_path, id:"logo" do
        = image_tag "logo.png", width: '200px'
      .right
        = form_tag escorts_path(), html:{role:"role"}, method: :get, remote: true do
          = text_field_tag :search, params[:search], placeholder:"Search for an Escort"
          = submit_tag 'Search'
    %div
      = link_to "Log Out", destroy_client_session_path, method: :delete

  .container
    .container.animated#buttons
      .row.text-center
        = link_to escorts_path(time_now: true), remote:true do
          %button#now Book Now
        = link_to escorts_path(time_now: false), remote:true do
          %button#later Book Later
  .container
    .container.animated#escorts

  .container
    .container.animated#appointment

      -#
        %h1 Our Beautiful Escorts!

        .container
          = form_tag '/escorts', html:{role:"role"}, method: :get do

            = text_field_tag :search, params[:search], placeholder:"Search a Username", autofocus: true
            = submit_tag 'Search'

          %hr

        .container
          .row
            - @escorts.each do |escort|
              .col-md-4
                .well.well-lg
                  .row
                    .col-xs-6
                      = link_to show_escort_path(escort.username) do
                        .container
                          %b= escort.username
                        .container
                          %b= escort.height
                          ,
                          %b= escort.weight
                        .container
                          PICTURES
                    .col-xs-6
                      = link_to "Create Appointment", new_appointment_path(escort_ID: escort.id)

app/views/clients/profile.html.haml
.container
  .text-center
    %h1 My Profile
  .jumbotron
    .row
      .col-md-4.col-md-offset-2
        %p Username
      .col-md-4
        %b= @client.username
    .row
      .col-md-4.col-md-offset-2
        %p Account Number
      .col-md-4
        %b= @client.token

  / DRY THIS OUT LATER!!!
  .panel.panel-default
    .panel-heading
      Past Appointments

    - if @past_appointments.empty?
      .panel-body
        No Past Appointments
    - @past_appointments.each do |appointment|
      .panel-body
        .row
          .col-xs-5
            = appointment.time
          .col-xs-5
            = appointment.location
          .col-xs-2
            = appointment.price / 100.00

  = link_to "Edit", edit_client_registration_path(@client)