config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :appointments, only: [:create, :new]

  devise_for :escorts
  devise_for :clients

  root 'statics#home'
  get 'home_client' => 'clients#home'#, as: "home_client"

  authenticated :client do
    get 'profile' => 'clients#profile', as: "profile_client"
  end

  authenticated :escort do
    get 'profile' => 'escorts#profile', as: "profile_escort"
  end

  get 'escorts' => 'escorts#index'
  get 'escorts/:username' => 'escorts#show', as: "show_escort"

end

app/models/escort.rb
class Escort < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable, :timeoutable, :authentication_keys => [:loginKey]

  # for generating random tokens (i.e. numbers)
  include Tokenable

  # for sending verification emails
  include VerifyEmail

  # appointments relationship
  has_many :appointments
  has_many :clients, through: :appointments
  has_many :onlineBlocks

  validates :username, presence: true
  validates :username, uniqueness: { case_sensitive: false}, if: -> { self.username.present? }
  validates :name, presence: true
  validates :dob, presence: true
  validates :line1, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :state, format: {with: /(^[A-Z]{2}$)/}, if: -> { self.state.present? }
  validates :zip, presence: true
  validates :zip, format: { with: /(^\d{5}$)|(^\d{5}-\d{4}$)/}, if: -> { self.zip.present? }

  validates :height, presence: true
  validates :weight, presence: true
  validates :ethnicity, presence: true
  validates :tit_size, presence: { message: "Breast size can't be blank"}
  validates :tit_type, presence: { message: "Breast type can't be blank"}
  validates :eyec, presence: { message: "Eye color can't be blank" }
  validates :hairc, presence: {message: "Hair color can't be blank"}

  validates :terms_of_service, acceptance: true

  attr_accessor :loginKey # for using either email or username

  # find the escort with either the given username or the given password
  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    if loginKey = conditions.delete(:loginKey)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", { :value => loginKey.downcase }]).first
    else
      where(conditions).first
    end
  end

  # only allow login if account is verified (by us)
  def active_for_authentication?
    super && self.verified
  end
end

app/controllers/escorts_controller.rb
class EscortsController < ApplicationController
  before_filter :authenticate_escort!, only: [:profile]

  def index
    if params[:time_now] == "true"
      @escorts = Escort.where(online: true)
    else
      @escorts = Escort.all
    end

    if !params[:search].blank?
      @escorts = Escort.where("username LIKE ? OR hairc LIKE ? OR eyec LIKE ? OR ethnicity LIKE ?", "%#{params[:search].downcase}%", "%#{params[:search]}%", "%#{params[:search]}%", "%#{params[:search]}%")
    end

    respond_to do |format|
      format.html
      format.js
    end
  end

  def show
    @escort = Escort.find_by_username(params[:username])
    # only allow appointments to be made by clients
    if client_signed_in?
      @client = current_client
      @appointment = Appointment.new
    end
  end

  def profile
    @escort = current_escort
    @past_appointments = @escort.appointments
  end
end

app/helpers/escorts_helper.rb
module EscortsHelper
end

app/views/escorts/_escort.html.haml
.col-md-3.escort-block-out{id: "escort#{escort.id}"}
  .escort-block-in.text-center
    = link_to new_appointment_path(escort_ID: escort.id, time_now: params[:time_now]), remote:true do
      = image_tag "escort-pics/escort#{escort.id}.png", width:'200px'

    -#
      %div.carousel.slide{id:"carousel-escort#{escort.id}", data:{ride:"carousel"}}
        -# Indicators
        %ol.carousel-indicators
          %li.active{data:{target:"#carousel-escort#{escort.id}", slide:{to:"0"}}}
          %li{data:{target:"#carousel-escort#{escort.id}", slide:{to:"1"}}}

        -# Wrapper for slides
        .carousel-inner{role:"listbox"}
          .item.active
            = image_tag "escort-pics/"+escort.username+"-1.png", alt:"#{escort.username}'s picture"
            .carousel-caption
              %p= escort.username
          .item.active
            = image_tag "escort-pics/"+escort.username+"-2.png", alt:"#{escort.username}'s picture"
            .carousel-caption
              %p= escort.username
        -# controls
        %a.left.carousel-control{href:"#carousel-escort#{escort.id}", role:"button", data:{slide:"prev"}}
          %span.glyphicon.glyphicon-chevron-left{aria:{hidden:"true"}}
          %span.sr-only Previous
        %a.right.carousel-control{href:"#carousel-escort#{escort.id}", role:"button", data:{slide:"next"}}
          %span.glyphicon.glyphicon-chevron-right{aria:{hidden:"true"}}
          %span.sr-only Previous

app/views/escorts/_escorts.html.haml
- if params[:time_now] == "true"
  %p displaying #{@escorts.count} escorts available near you, tonight
- else
  %p displaying the #{@escorts.count} escorts meeting your derived preferences

.row
  - @escorts.each do |e|
    = render e

app/views/escorts/index.html.haml
.container
  %h1 Our Beautiful Escorts!

  .container
    = form_tag '/escorts', html:{role:"role"}, method: :get do

      = text_field_tag :search, params[:search], placeholder:"Search a Username", autofocus: true
      = submit_tag 'Search'

    %hr

  .container
    .row
      - @escorts.each do |e|
        = render e
      -#
        .col-md-4
          .well.well-lg
            .row
              .col-xs-6
                = link_to show_escort_path(escort.username) do
                  .container
                    %b= escort.username
                  .container
                    %b= escort.height
                    ,
                    %b= escort.weight
                  .container
                    PICTURES
              .col-xs-6
                = link_to "Create Appointment", new_appointment_path(escort_ID: escort.id)

app/views/escorts/index.js.erb
$("#clients #buttons").addClass("fadeOutUp hideMe");
$("#clients #buttons").removeClass("fadeInDown");

<% if params[:time_now] == "true" %>
  $("#clients #buttons #now").addClass("chosen");
  $("#clients #buttons #later").removeClass("chosen");
<% else %>
  $("#clients #buttons #later").addClass("chosen");
  $("#clients #buttons #now").removeClass("chosen");
<% end %>

$("#clients #escorts").html("<%= escape_javascript(render "escorts/escorts") %>");
$("#clients #escorts").removeClass("fadeOutDown hideMe")
$("#clients #escorts").addClass("fadeInUpBig");

gon.page = "escorts";

app/views/escorts/profile.html.haml
.container
  .text-center
    %h1 My Profile
  .jumbotron
    .row
      .col-md-4.col-md-offset-2
        %p Username
      .col-md-4
        %b= @escort.username
    .row
      .col-md-4.col-md-offset-2
        %p Account Number
      .col-md-4
        %b= @escort.token

  / DRY THIS OUT LATER!!!
  .panel.panel-default
    .panel-heading
      Past Appointments
    .panel-body
      - if @past_appointments.empty?
        No Past Appointments
      - @past_appointments.each do |appointment|
        .row
          .col-md-2.col-md-offset-2
            = appointment.time
          .col-md-2.col-md-offset-2
            = appointment.location
          .col-md-2.col-md-offset-2
            = appointment.price

  = link_to "Edit", edit_escort_registration_path(@client)

app/views/escorts/show.html.haml
.container
  .text-center
    %h1
      The Wonderful
      = @escort.username
  .jumbotron
    .row
      .col-xs-4.col-xs-offset-2
        %p Height
      .col-xs-4
        %b= @escort.height
    .row
      .col-xs-4.col-xs-offset-2
        %p Weight
      .col-xs-4
        %b= @escort.weight
    .row
      .col-xs-4.col-xs-offset-2
        %p Ethnicity
      .col-xs-4
        %b= @escort.ethnicity
    .row
      .col-xs-4.col-xs-offset-2
        %p Eye Color
      .col-xs-4
        %b= @escort.eyec
    .row
      .col-xs-4.col-xs-offset-2
        %p Hair Color
      .col-xs-4
        %b= @escort.hairc

    PICTURES

- if client_signed_in?
  .container
    = render file: 'appointments/new'