config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :appointments, only: [:create, :new]

  devise_for :escorts
  devise_for :clients

  root 'statics#home'
  get 'home_client' => 'clients#home'#, as: "home_client"

  authenticated :client do
    get 'profile' => 'clients#profile', as: "profile_client"
  end

  authenticated :escort do
    get 'profile' => 'escorts#profile', as: "profile_escort"
  end

  get 'escorts' => 'escorts#index'
  get 'escorts/:username' => 'escorts#show', as: "show_escort"

end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def home
    if client_signed_in?
      redirect_to home_client_path
    end
  end
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/statics/1home.html.erb
<body id="page-top" class="body" data-spy="scroll" data-target=".navbar-fixed-top">
    <!-- Navigation -->
    <nav class="navbar navbar-custom navbar-fixed-top" role="navigation">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-main-collapse">
                    <i class="fa fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                    <ul class="nav navbar-nav">
		                    <li>
		                        <%= link_to "Invest", "#invest"%>
		                    </li>
		                    <li>
		                        <%= link_to "Explore", "#cars" %>
		                    </li>
		                </ul>
		            </div>
            </div>

            <a class="navbar-brand page-scroll nav-center" href="#page-top">
                Black Goose
            </a>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse navbar-right navbar-main-collapse">
                <ul class="nav navbar-nav">
                    <!-- Hidden li included to remove active class from about link when scrolled up past about section -->
                    <li class="hidden">
                        <a href="#page-top"></a>
                    </li>

                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Intro Header -->
    <header class="intro">
        <div class="intro-body">
            <div class="container">
                <div class="row">
                    <div class="col-md-8 col-md-offset-2">
                        <h1 class="brand-heading">shift your dream into gear</h1>
                        <p class="intro-text">exotic cars that are just around the corner.</p>
                        <a href="#about" class="btn btn-circle page-scroll">
                            <i class="fa fa-angle-double-down fa-lg animated" style="position:relative"></i>
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Welcome to the World of Luxautic</h2>
								<p> Welcome to the world of Luxautic. From the first click to the final mile, our clients don't just get a car - they get an experience unlike any other. Our inventory boasts the finest luxury and exotic vehicles the world has to offer.</p>
								<p>From Aston Martins and Bentleys to Ferraris and Porsches, we have vehicles in every make, shape and flavor, so you're sure to find exactly what you're looking for.</p>
								<p>For the young couple looking to have a fun weekend in a new Audi R8 or for the itinerant business man who needs a Porsche for the weekend, Luxautic is a company for people going places.</p>
								<p>Where are you going?</p>

								<a href="#explore" class="btn btn-circle page-scroll btn-circle-black">
                    <i class="fa fa-car animated icon-black" style="position:relative"></i>
                </a>
            </div>
        </div>
    </section>

    <!-- Explore Section -->
    <section id="explore" class="content-section text-center">
        <div class="explore-section">
            <div class="container">
                <div class="col-lg-8 col-lg-offset-2">
                    <h2>Explore our Fleet</h2>
                    <p>Browse our immaculately maintained and widely respected<br>fleet of exotic and luxury cars.</p>
                    <a href="#fleet" class="btn btn-default btn-lg">Explore</a>
                </div>


            </div>

        </div>
				<a href="#team" class="btn btn-circle page-scroll btn-circle-black">
            <i class="fa fa-users animated icon-black" style="position:relative;"></i>
        </a>
    </section>

    <!-- Contact Section -->
    <section id="contact" class="container content-section text-center">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2">
                <h2>Reach Luxautic</h2>
                <p>Feel free to email or call us to provide feedback, give us suggestions,<br>ask questions, or just talk about cars!</p>
                <p><a href="mailto:info@luxautic.com">info@luxautic.com</a>
                </p>
                <ul class="list-inline banner-social-buttons">
                    <li>
                        <a href="https://twitter.com/luxautic" class="btn btn-default btn-lg"><i class="fa fa-twitter fa-fw"></i> <span class="network-name">Twitter</span></a>
                    </li>
                    <li>
                        <a href="https://facebook.com/luxautic" class="btn btn-default btn-lg"><i class="fa fa-facebook fa-fw"></i> <span class="network-name">Facebook</span></a>
                    </li>
                    <li>
                        <a href="https://plus.google.com/+MatthewVasseur/posts" class="btn btn-default btn-lg"><i class="fa fa-linkedin fa-fw"></i> <span class="network-name">LinkedIn</span></a>
                    </li>
                </ul>
            </div>
        </div>
				<a href="#map" class="btn btn-circle page-scroll btn-circle-black">
            <i class="fa fa-globe animated icon-black" style="position:relative; top:-4px"></i>
        </a>
    </section>

    <!-- Map Section -->
    <div id="map"></div>

    <!-- Footer -->
    <footer>
        <div class="container text-center">
            <p>Copyright &copy; Luxautic Limited 2014</p>
        </div>
    </footer>

    <!-- Google Maps API Key - Use your own API key to enable the map feature. More information on the Google Maps API can be found at https://developers.google.com/maps/ -->
    <script type="text/javascript" src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDosD3oNPhXZVudPwGz3GXMqnlBZTt-IeI&sensor=true"></script>

		<!-- Custom javascript grayscale.js file loaded after google api -->
		<%= javascript_include_tag 'grayscale.js' %>

</body>

app/views/statics/home.html.haml
%body#page-top.body{data: {spy: "scoll", target: "navbar-fixed-top"}}
  %nav.navbar.navbar-custom.navbar-fixed-top{role:"navigation"}
    .container
      .navbar-header
        %button.navbar-toggle{type: "button", |
        data: {toggle:"collapse", target:".navbar-main-collapse"}} |
          %i.fa.fa-bars
        .collapse.navbar-collapse.navbar-right.navbar-main-collapse
          %ul.nav.navbar-nav
            - if client_signed_in?
              %li
                = link_to "Log Out", destroy_client_session_path, method: :delete
              %li
                = link_to "My Profile", profile_client_path
              %li
                = link_to "Escorts", escorts_path

            - elsif escort_signed_in?
              %li
                = link_to "Log Out", destroy_escort_session_path, method: :delete
              %li
                = link_to "My Profile", profile_escort_path

            -else
              %li
                = link_to "Escort", new_escort_session_path
              %li
                = link_to "Client", new_client_session_path

      %a.navbar-brand.page-scroll.nav-center{href:"#page-top"}
        Black Goose

      .collapse.navbar-collapse.navbar-right.navbar-main-collapse
        %ul.nav.navbar-nav
          %li.hidden
            %a{href:"#page-top"}
  / Intro Section
  %header.intro
    .intro-body
      .container
        .row
          .col-md-8.col-md-offset-2
            %h1.brand-heading instant escort booking
            %p.intro-text the world's first and largest platform for booking escorts
            %a.btn-circle.page-scroll{href:"#about"}
              %i.fa.fa-angle-double-down.animated

  / About Section
  %section#about.container.content-section.text-center
    .row
      .col-lg-8.col-lg-offset-2
        %h2 Welcome to Black Goose
        %p Lorem shut the shizzle up dolizzle sit amizzle, bling bling adipiscing elit.
        %p Nullam sapien velit, owned volutpizzle, suscipizzle owned, ma nizzle vel, cool. P
        %p Pellentesque eget tortor. Sizzle erizzle. Ghetto izzle black dapibus tempus check it.
        %p For sure ass nibh izzle hizzle. Fo shizzle my nizzle fo shizzle tortor. Boofron bling.

        %a.btn-circle.page-scroll.btn-circle-black{href:"#explore"}
          %i.fa.fa-car.animated.icon-black

  / Explore Section
  %section#explore.content-section.text-center
    .explore-section
      .container
        .col-lg-8.col-lg-offset-2
          %h2 Don't Explore Alone...
          %p allow our wonderful escorts to be by your side
          %a.btn.btn-default.btn-lg{href:"#escorts"} Explore

  / Contact Section
  %section#contact.container.content-section.text-center
    .row
      .col-lg-8.col-lg-offset-2
        %h2 Reach Black Goose
        %p email or call
        %a{href:"mailto:matt@black-goose.com"} Matt Vasseur
        %ul.list-inline.banner-social-buttons
          %li
            %a.btn.btn-default.btn-lg{href:"https://twitter.com/#black-goose"}
              %i.fa.fa-twitter.fa-fw
                %span.network-name Twitter

  %footer
    .container.text-center
      %p Copyright &copy; Black Goose

= javascript_include_tag 'grayscale.js'